cafe/urls.py
from django.urls import path

from . import views

app_name = "cafe"

urlpatterns = [
    path("", views.CategoryLV.as_view(), name="index"),      # 제네릭 뷰 사용
    path("<int:pk>/", views.MenuLV.as_view(), name="detail"),
    path("<int:pk>/<int:pk2>", views.MenuDV.as_view(), name="menudetail"),
    path('create/', views.CategoryCV.as_view(), name='category_create'),
    path('menu/create/', views.MenuCV.as_view(), name='menu_create'),
    path('<int:category_id>/<int:menu_id>/order/', views.OrderView.as_view(), name='order'),
    path('manage/', views.ManageView.as_view(), name='manage'),
    path('<int:pk>/order/', views.PayView.as_view(), name='pay'),
    path('order/pay', views.PaySuccessView.as_view(), name='pay_success'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name = 'home'),
    path('admin/', admin.site.urls, name='admin'),
    path('cafe/',include('cafe.urls')),
]

cafe/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(verbose_name='CATEGORY NAME', max_length=200)
    
    def __str__(self):
        return self.name


class Menu(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='MENU NAME', max_length=50, unique=True)
    price = models.IntegerField(verbose_name='PRICE', default=0)

    def __str__(self):
        return self.name

class Order(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name="PRICE", default=0)
    quantity = models.IntegerField(verbose_name="QUANTITY", default=0)
    ice = models.BooleanField(verbose_name='ICE', default=True)
    pay = models.BooleanField(verbose_name='PAY', default=False)
    

cafe/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView
from django.urls import reverse, reverse_lazy
from django.http import Http404, HttpResponse
from cafe.models import Category, Menu, Order
# Create your views here.

class CategoryLV(ListView):
    model = Category

class CategoryDV(DetailView):
    model = Category
    
class MenuLV(ListView):
    model = Menu
    
    def get_queryset(self):
        category_pk = self.kwargs.get('pk')
        
        queryset = Menu.objects.filter(category__id = category_pk)
        
        return queryset
    
class MenuDV(DetailView):
    model = Menu
    
    def get_object(self, queryset=None):
        category_pk = self.kwargs.get('pk')
        menu_pk = self.kwargs.get('pk2')
        
        try:
            queryset = Menu.objects.get(category__id=category_pk, id=menu_pk)
        except Menu.DoesNotExist:
            raise Http404("Menu does not exist")
        
        return queryset
    
class ManageView(TemplateView):
    template_name = 'cafe/manage.html'
    
class MenuCV(CreateView):
    model = Menu
    fields = ['name', 'price', 'category']
    success_url = reverse_lazy('cafe:index')
    
class CategoryCV(CreateView):
    model = Category
    fields = ['name']
    success_url = reverse_lazy('cafe:index')
    
class OrderView(TemplateView):
    template_name = 'cafe/order.html'

    def post(self, request, category_id, menu_id):
        quantity = request.POST.get('quantity')
        ice = request.POST.get('ice')
        menu = Menu.objects.get(pk=menu_id)
        price = menu.price
        order = Order.objects.create(menu=menu, quantity=quantity, ice=ice, price = int(price)*int(quantity))
        return render(request, self.template_name, {'order': order})

class PayView(UpdateView):
    model = Order
    fields=['pay']
    template_name = 'cafe/pay.html'
    def get_success_url(self):
        return reverse_lazy('cafe:pay_success')
    
class PaySuccessView(TemplateView):
    template_name = "cafe/pay_success.html"
    

config/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

cafe/templates/cafe/category_detail.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Bookmark List{% endblock %}
{% block content %}

<br>
<div>
    <h3>TITLE : {{category.name}}</h3>

</div>
{% endblock content %}

cafe/templates/cafe/category_form.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Create Menu{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    
    {% for field in form %}
    {{form.as_p}}
    {% endfor %}
    <div class='mb-2'>
        <button type="submit" class="btn btn-primary">완료</button>
    </div>
</form>
<!-- 뒤로 가기 버튼 -->
<button onclick="goBack()" class="btn btn-secondary">뒤로 가기</button>

<script>
    function goBack() {
        window.history.back();
    }
</script>
{% endblock content %}

cafe/templates/cafe/category_list.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Category List{% endblock %}
{% block content %}

<ul style="list-style-type: none; padding: 0;">
    {% for category in object_list %}
    <li style="display: inline-block; margin-right: 10px;"> <!-- 각 카드 요소를 인라인 블록으로 설정하고 우측 마진 추가 -->
        <div class="card" style="width: 18rem;">
            {% comment %} <img src="{% static 'img/coffee.png' %}" class="card-img-top"> {% endcomment %}
            <div class="card-body">
                <h5 class="card-title">{{ category.name }}</h5>
                <p class="card-text">menu category content</p>
                <a href="{% url 'cafe:detail' category.id %}" class="btn btn-primary">{{category.name}}</a>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
<!-- 뒤로 가기 버튼 -->
<div class="mb-2"> 
    <button onclick="goBack()" class="btn btn-secondary">뒤로 가기</button>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>

<div class="mb-2"> 
    <form method="get" action="{% url 'cafe:category_create' %}">
        <button type="submit" class="btn btn-secondary">카테고리 추가하기 </button>
    </form>
</div>
{% endblock content %}

cafe/templates/cafe/manage.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Manage{% endblock %}
{% block content %}

<div class="mt-3">
    <div class="mb-2"> <!-- 버튼 사이에 패딩을 추가할 div 요소 -->
        <form method="get" action="{% url 'cafe:menu_create' %}">
            <button type="submit" class="btn btn-secondary">추가하기</button>
        </form>
    </div>
    <div class="mb-2"> <!-- 버튼 사이에 패딩을 추가할 div 요소 -->
        <form method="get" action="{% url 'cafe:manage' %}">
            <button type="submit" class="btn btn-secondary">수정하기</button>
        </form>
    </div>
    <div> <!-- 버튼 사이에 패딩을 추가할 div 요소 -->
        <form method="get" action="{% url 'cafe:manage' %}">
            <button type="submit" class="btn btn-secondary">삭제하기</button>
        </form>
    </div>
</div>
{% endblock content %}

cafe/templates/cafe/menu_detail.html
{% extends 'base.html' %}

{% load static %}
{% block title %}메뉴 상세페이지{% endblock %}
{% block content %}

<br>
<div>
    <h3>{{menu.name}}</h3>
    가격 : {{menu.price}}
    카테고리: {{menu.category.name}}
</div>

<form method="post" action="{% url 'cafe:order' menu.category.id menu.id%}">
    {% csrf_token %}
    수량: <input type="number" name="quantity" value="1" min="1">
    <label for="ice">Hot / Ice:</label>
    <select id="ice" name="ice">
        <option value="True">Ice</option>
        <option value="False">Hot</option>
    </select>
    <button type="submit" class="btn btn-secondary">주문하기</button>
</form>

<!-- 뒤로 가기 버튼 -->
<div class="mb-2"> 
<button onclick="goBack()" class="btn btn-secondary">뒤로 가기</button>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>
{% endblock content %}

cafe/templates/cafe/menu_form.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Create Menu{% endblock %}
{% block content %}

<div class='mb-2'>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class='btn btn-primary'>메뉴 추가하기</button>
    </form>
</div>
<!-- 뒤로 가기 버튼 -->
<div class = 'mb-2'>
    <button onclick="goBack()" class="btn btn-secondary">뒤로 가기</button>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

{% endblock content %}

cafe/templates/cafe/menu_list.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Menu List{% endblock %}
{% block content %}

<br>

<ul>
    {% for menu in object_list %}
    <li style="display: inline-block; margin-right: 10px;">
    <div class="card" style="width: 18rem;">
        <img src="{% static 'img/coffee.png' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ menu.name }}</h5>
          <p class="card-text">메뉴 설명 ~~ .</p>
          <a href="{% url 'cafe:menudetail' menu.category.id menu.id %}" class="btn btn-primary">{{ menu.name }}</a>
        </div>
      </div>
    </li>
    {% endfor %}
</ul>
<!-- 뒤로 가기 버튼 -->
<div class="mb-2"> 
    <button onclick="goBack()" class="btn btn-secondary">뒤로 가기</button>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

<div class='mb-2'>
    <form method="get" action="{% url 'cafe:menu_create' %}">
        <button type="submit" class="btn btn-secondary">메뉴 추가하기 </button>
    </form>
</div>
{% endblock content %}

cafe/templates/cafe/order.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Order{% endblock %}
{% block content %}

<p>메뉴: {{ order.menu }}</p>
{% if order.ice %}
    <p>아이스: ice</p>
{% else %}
    <p>아이스: hot</p>
{% endif %}
<p>수량: {{ order.quantity }}</p>
<p>가격: {{ order.price }}</p>

<form method="post" action="{% url 'cafe:pay' order.id%}">
    {% csrf_token %}
    <input type="hidden" name="order_id" value="{{ order.id }}">
    <button type="submit" class="btn btn-secondary">결제하기</button>
</form>

{% endblock content %}

cafe/templates/cafe/pay.html
결제 완료

cafe/templates/cafe/pay_success.html
{% extends 'base.html' %}

{% load static %}
{% block title %}결제 완료{% endblock %}
{% block content %}

<div class='mb-2'>
    <form method="get" action="{% url 'home' %}">
        <button type="submit" class='btn btn-primary'>홈</button>
    </form>
</div>
<div class='mb-2'>
    <form method="get" action="{% url 'cafe:index' %}">
        <button type="submit" class="btn btn-primary">추가 주문하기 </button>
    </form>
</div>

<script>
    function showPaymentSuccessMessage() {
        var message = "결제가 성공적으로 완료되었습니다.";  
        alert(message);  
    }

    window.onload = function() {
        showPaymentSuccessMessage();
    };
</script>

{% endblock content%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Like Lion {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block extra-style %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Cafe Kiosk</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'cafe:index' %}">Menu</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'cafe:manage' %}">Manage</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="/admin">Admin</a>
              </li>

                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="bg-light">
        {% block content %}{% endblock %}
    </div>

      {% block footer %}
      <footer class="footer mt-auto py-3">
        <div class="container text-center">
            <span class="text-muted">카페 키오스크 앱에 오신 것을 환영합니다!</span><br>
            <span class="text-muted">이용약관 | 개인정보 처리방침 | 고객센터</span><br>
            <span class="text-muted">주소: 서울특별시 OO구 OO동 123-45 카페 키오스크</span><br>
            <span class="text-muted">전화번호: 02-1234-5678 | 이메일: info@cafekiosk.com</span>
        </div>
    </footer>
    {% endblock %}
</body>

templates/home.html
{% extends 'base.html' %}

{% load static %}
{% block title %}카페 키오스크{% endblock %}
{% block extra-style %}
<style type="text/css">
    .home-image {
        background-image: url("{% static 'img/cafe_img.png' %}");
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100%;
        height: 500px;
        border-top: 10px solid #ccc;
        border-bottom: 10px solid #ccc;
        padding: 20px 0 0 20px;
        opacity: 0.7;
    }
    .title {
        color: #c80;
        font-weight: bold;
    }
    .powered {
        position: relative;
        top: 77%;
        color: #cc0;
        font-style: italic;
    }
    </style>
{% endblock %}
{% block content %}
    <div class = 'home-image'>
        <h2 class = 'title'>Cafe</h2>
        <h4 class = 'powered'><i class ='fas fa-arrow-circle-right'></i></h4>
    </div>
{% endblock content %}